config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  # Routes for authentication
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  # Route for the cat facts
  resources :cat_facts, only: [:index]

  # Routes for the favorites
  resources :favorites, only: [:index, :create, :destroy]
  get '/community', to: 'favorites#community'

  # Routes for Not Found page
  get '*path', to: 'application#not_found', via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat_fact.rb
class CatFact < ApplicationRecord
    # content must be present and unique
    validates :fact, presence: true, uniqueness: true

    has_many :favorites, dependent: :destroy
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, uniqueness: { scope: :cat_fact_id }
  belongs_to :user
  belongs_to :cat_fact
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorites, dependent: :destroy
    has_many :cat_facts, through: :favorites

    # username must be present, unique, between 2 and 20 characters long, and only contain letters and numbers
    validates :username,
        presence: true, uniqueness: true,
        length: { in: 2..20 },
        format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters and numbers"}

    before_save :downcase_username

    private

    # downcase the username before saving
    def downcase_username
        self.username.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    before_action :protect_pages
    skip_before_action :protect_pages, only: [:index]

    def index
    end

    def not_found
    end

    private

    # Set the current user for the session if the user is logged in
    def set_current_user
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end

    # Redirect to the login page if the user is not logged in
    def protect_pages
        redirect_to new_session_path, alert: "You must be logged in to access this page" unless Current.user
    end
    
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
    skip_before_action :protect_pages
    
    def new
    end

    # Create a new user
    def create
        @user = User.find_by(username: params[:username].downcase)
        if @user
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Logged in successfully!"
        else
            redirect_to new_session_path, alert: "Invalid username"
        end
    end

    # Destroy the current session
    def destroy
        session.delete(:user_id)
        redirect_to new_session_path, notice: "Logged out successfully!"
    end

end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
    skip_before_action :protect_pages
    
    # Display the sign up form
    def new
        @user = User.new
    end

    # Create a new user
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "User created successfully!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    private 

    # params required for user creation
    def user_params
        params.require(:user).permit(:username)
    end
end

app/controllers/cat_facts_controller.rb
require 'httparty'

class CatFactsController < ApplicationController
    before_action :protect_pages

    def index
        begin
            # Get a random cat fact from the API
            response = HTTParty.get('https://catfact.ninja/fact')
            if response.success?
                message = response.parsed_response['fact']
        
                # Save the fact to the database
                cat_fact = CatFact.new(fact: message)
                if cat_fact.save
                    @fact = fact_db(message)
                    @added_to_favorites = false
                else
                # If the fact already exists in the database, display the fact from the database
                    @fact = fact_db(message)
                    @added_to_favorites = Favorite.exists?(user_id: Current.user.id, cat_fact_id: CatFact.find_by(fact: message).id)
                end
            else
                @fact = 'No cat facts available at the moment. Please try again later.'
            end
        rescue StandardError => e
            @fact = 'No cat facts available at the moment. Please try again later.'
            Rails.logger.error "Had an issue with the cat facts API: #{e}"
        end
    end

    private

    def fact_db(message)
        CatFact.find_by(fact: message).fact
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :protect_pages

    # Display the favorite cat facts for the current user
    def index
        @favorites = Favorite.where(user_id: Current.user.id)
    end

    # Add a favorite cat fact to the database for the current user
    def create
        Favorite.create(user_id: Current.user.id, cat_fact_id: params[:cat_fact_id])
        @added_to_favorites = true
        redirect_to favorites_path
    end

    # Remove a favorite cat fact from the database for the current user
    def destroy
        Favorite.find_by(user_id: Current.user.id, cat_fact_id: params[:id]).destroy
        @added_to_favorites = false
        redirect_to favorites_path
    end
    
    # Display most favorited cat facts for the community
    def community
        @favorites = Favorite.group(:cat_fact_id).count
        @top_facts = Favorite.group(:cat_fact).count.sort_by { |_, count| -count }.first(3) || []
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_facts_helper.rb
module CatFactsHelper

    # Obtains id of the cat fact, if it exists in the database else returns -1 
    def get_fact_id
        cat_fact = CatFact.find_by(fact: @fact)
        cat_fact ? cat_fact.id : -1
    end
end

app/views/application/index.html.erb
<h1 class="text-3xl font-bold mb-6">SSCatFacts 😺</h1>

<% if !Current.user %>
    <p class="text-lg mb-4">Please login or sign up to see a cat fact</p>
    <div class="flex text-white font-bold mb-4">
        <%= link_to "Login", new_session_path, class: "bg-blue-500 hover:bg-blue-700 py-2 px-4 rounded mr-8" %>
        <%= link_to "Sign in", new_user_path, class: "bg-blue-500 hover:bg-blue-700 py-2 px-4 rounded" %>
    </div>
<% else %>
    <p class="text-lg" >Welcome <%= Current.user.username %> !</p>
    <p class="mb-4">See and save your favorite cat facts</p>

    <div class="flex text-white font-bold mb-4 w-full">
        <%= link_to "Cat Fact 😺", cat_facts_path, class: "bg-blue-500 hover:bg-blue-700 py-2 px-6 rounded mr-6" %>
        <%= link_to "My Favorites 💖", favorites_path, class: "bg-red-500 hover:bg-red-600 py-2 px-6 rounded" %>
    </div>
        
    <%= link_to "Favorites facts from the community 🌟", community_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mb-6" %>
    <%= link_to "Logout", session_path(Current.user.id), data: { turbo_method: :delete }, class: "bg-red-700 hover:bg-red-800 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/application/not_found.html.erb
<h1 class="text-3xl font-bold mb-6">This page does not exist</h1>

<%= link_to "Go back to the home page", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

app/views/authentication/_form.html.erb
<div class="mb-4">
    <%= form.label :username, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :username, required: true, class: "shadow border rounded w-full py-2 px-3" %>
</div>

app/views/authentication/users/new.html.erb
<h1 class="text-3xl font-bold mb-8">Sign In</h1>

<%= form_with(model: @user) do |form| %>
    <% @user.errors.full_messages.each do |message| %>
        <div class="mb-4 text-red-700">
            <%= message %>
        </div>
    <% end %>
    
    <%= render "authentication/form", form: form %>

    <div class="flex justify-center">
        <%= form.submit "Register", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
<% end %>

<div class="mt-4">
    <p> Already have an account? <%= link_to "Log In", new_session_path, class: "text-blue-500 hover:text-blue-700 underline font-bold" %></p>
</div>

app/views/cat_facts/_favorite_button.html.erb
<% if get_fact_id != -1 %>
    <% if @added_to_favorites %>
        <%= link_to "Remove from Favorites 💔", favorite_path(get_fact_id), data: { turbo_method: :delete }, class: "bg-red-400 hover:bg-red-600 py-2 px-4 rounded mr-4" %>
    <% else %>
        <%= link_to "Add to Favorites 💖", favorites_path(cat_fact_id: get_fact_id), data: { turbo_method: :post }, class: "bg-red-600 hover:bg-red-700 py-2 px-4 rounded mr-4" %>
    <% end %>
<% end %>

app/views/cat_facts/index.html.erb
<h1 class="text-3xl font-bold mb-4">Cat Fact 😺</h1>

<p class="mb-2 font-bold">Here is a cat fact for you:</p>
<p><span class="font-bold">#Fact <%= get_fact_id %></span> <%= @fact %></p>
<div class="flex text-white font-bold mt-4 text-center"> 
    <%= link_to "Get Another Fact 🐱", cat_facts_path, data: {turbo_method: :get}, class: "bg-blue-500 hover:bg-blue-700 py-2 px-4 rounded mr-4" %>
    <%= render partial: "cat_facts/favorite_button", locals: { added_to_favorites: @added_to_favorites } %>
</div>

app/views/favorites/community.html.erb
<h1 class="text-3xl font-bold mb-6 text-center">Community Favorites 🌟</h1>
<h2 class="text-xl font-bold mb-4 text-center">Top 3 Favorites 🏅</h2>

<% if @favorites.any? %>
    <ul class="text-left">
    <% @top_facts.each_with_index do |(fact, count), index| %>
        <li class="flex justify-between border-b-2 border-gray-200 py-4 px-2">    
            <% medals = ["🥇", "🥈", "🥉"] %>
            <%= medals[index] %> 
            <p class="mx-4"><span class="font-bold">Fact #<%= fact.id %> </span><%= fact.fact %></p>
            <p class="text-center font-bold">💖 <%= count %></p>
        </li>
    <% end %>
    </ul>
<% else %>
    <p>No favorites yet. <%= link_to "Start adding some!", cat_facts_path, class: "text-blue-500 font-bold" %></p>
<% end %>

app/views/favorites/index.html.erb
<h1 class="text-3xl font-bold mb-6">My Favorites 💖</h1>

<% if @favorites.any? %>
    <ul class="w-full">
        <% @favorites.reverse_each do |favorite| %>
            <li class="flex items-center justify-between border-b-2 border-gray-200 py-4 px-2 hover:bg-slate-200">                    
                <p><span class="font-bold">#Fact <%= favorite.cat_fact.id%></span> <%= favorite.cat_fact.fact %></p>
                <%= link_to "💔", favorite_path(favorite.cat_fact.id), data: {turbo_method: :delete} %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p class="text-xl font-bold mb-2">You don't have any favorites yet!</p>
    <p>Go to the <a href="/cat_facts" class="text-blue-500 font-bold">Cat Facts</a> page to add some!</p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="flex justify-between items-center fixed z-10 top-0 w-full py-5 px-6 text-sm bg-white font-light">
    <div class="flex items-center">
        <div class="mr-6">
            <%= link_to "SSCatFacts 😺", root_path, class: "text-blue-300 font-semibold text-xl" %>
        </div>
    </div>
    <div class="md:hidden">
        <button id="menu-toggle" class="focus:outline-none">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
        </button>
    </div>
    <ul id="menu" class="hidden md:flex items-center gap-4 font-bold">
        <% if !Current.user %>
            <li class="border-2 border-sky-500 hover:bg-sky-400 shadow-lg rounded-lg p-2"> <%= link_to "Login", new_session_path %></li>
            <li class="border-2 border-sky-500 hover:bg-sky-400 shadow-lg rounded-lg p-2"><%= link_to "Sign in", new_user_path %></li>
        <% else %>
            <li class="border-2 border-sky-500 hover:bg-sky-400 shadow-lg rounded-lg p-2"><%= link_to "Cat Fact 😺", cat_facts_path%></li>
            <li class="border-2 border-red-500 hover:bg-red-400 shadow-lg rounded-lg p-2"><%= link_to "My Favorites 💖", favorites_path %></li>
            <li class="border-2 border-green-500 hover:bg-green-400 shadow-lg rounded-lg p-2"><%= link_to "Favorites facts from the community 🌟", community_path %></li>
            <li class="border-2 border-red-800 hover:bg-red-700 shadow-lg rounded-lg p-2"><%= link_to "Logout", session_path(Current.user.id), data: { turbo_method: :delete } %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSCatFacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "menu-toggle" %>
    <%= javascript_include_tag "disable_turbo_links" %>
  </head>

  <body  class="flex flex-col min-h-screen bg-blue-900">

    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <main class="flex-grow flex items-center justify-center">
      <div class="flex flex-col items-center justify-center bg-white p-10 rounded-lg shadow-lg shadow-black max-w-xl mt-24 mb-6 mx-4">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<p class="text-green-600"><%= notice %></p>